# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/vga_ram/vga_ram.xci
# IP: The module: 'vga_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/vga_ram/vga_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: g:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/vga_ram/vga_ram.xci
# IP: The module: 'vga_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/vga_ram/vga_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
