# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/prj5_apollo-master-3bd193289902d4aded5121b45787793f054fa79c/mips/NEHCPU/NEHCPU.srcs/sources_1/ip/clk_func/clk_func.xci
# IP: The module: 'clk_func' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/prj5_apollo-master-3bd193289902d4aded5121b45787793f054fa79c/mips/NEHCPU/NEHCPU.srcs/sources_1/ip/clk_func/clk_func_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_func'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: g:/prj5_apollo-master-3bd193289902d4aded5121b45787793f054fa79c/mips/NEHCPU/NEHCPU.srcs/sources_1/ip/clk_func/clk_func.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_func'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: g:/prj5_apollo-master-3bd193289902d4aded5121b45787793f054fa79c/mips/NEHCPU/NEHCPU.srcs/sources_1/ip/clk_func/clk_func_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_func'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: g:/prj5_apollo-master-3bd193289902d4aded5121b45787793f054fa79c/mips/NEHCPU/NEHCPU.srcs/sources_1/ip/clk_func/clk_func_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_func'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: G:/prj5_apollo-master-3bd193289902d4aded5121b45787793f054fa79c/mips/NEHCPU/NEHCPU.srcs/sources_1/ip/clk_func/clk_func.xci
# IP: The module: 'clk_func' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/prj5_apollo-master-3bd193289902d4aded5121b45787793f054fa79c/mips/NEHCPU/NEHCPU.srcs/sources_1/ip/clk_func/clk_func_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_func'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: g:/prj5_apollo-master-3bd193289902d4aded5121b45787793f054fa79c/mips/NEHCPU/NEHCPU.srcs/sources_1/ip/clk_func/clk_func.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_func'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: g:/prj5_apollo-master-3bd193289902d4aded5121b45787793f054fa79c/mips/NEHCPU/NEHCPU.srcs/sources_1/ip/clk_func/clk_func_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_func'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: g:/prj5_apollo-master-3bd193289902d4aded5121b45787793f054fa79c/mips/NEHCPU/NEHCPU.srcs/sources_1/ip/clk_func/clk_func_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_func'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
