# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/scfifo/scfifo.xci
# IP: The module: 'scfifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/scfifo/scfifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'scfifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/scfifo/scfifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/scfifo/scfifo.xci
# IP: The module: 'scfifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/scfifo/scfifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'scfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: g:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/scfifo/scfifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scfifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
