# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tfgg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.cache/wt [current_project]
set_property parent.project_path G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/defines.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/wb_conmax/wb_conmax_defines.v
}
set_property file_type "Verilog Header" [get_files G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/defines.v]
set_property file_type "Verilog Header" [get_files G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/wb_conmax/wb_conmax_defines.v]
read_mem G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/inst_rom.data
read_verilog -library xil_defaultlib {
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/clk_master.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/cp0_reg.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/ctrl.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/ex.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/ex_mem.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/new/fifo_wrapper.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/hilo_reg.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/id.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/id_ex.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/if_id.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/inst_rom_top.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/mem.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/mem_wb.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/mmu.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/nehcpu.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/pc_reg.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/regfile.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/sram.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/prjNEHtest/uart_async.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/prjNEHtest/uart_controller.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/new/vga_slave.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/vir2phy.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/wb_conmax/wb_conmax_arb.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/wb_conmax/wb_conmax_master_if.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/wb_conmax/wb_conmax_msel.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/wb_conmax/wb_conmax_pri_dec.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/wb_conmax/wb_conmax_pri_enc.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/wb_conmax/wb_conmax_rf.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/wb_conmax/wb_conmax_slave_if.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/wb_conmax/wb_conmax_top.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/wb_flash.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/wishbone_bus.v
  G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/imports/src/nehcpu_sopc.v
}
read_ip -quiet G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/scfifo/scfifo.xci
set_property used_in_implementation false [get_files -all g:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/scfifo/scfifo.xdc]
set_property used_in_implementation false [get_files -all g:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/scfifo/scfifo_ooc.xdc]
set_property is_locked true [get_files G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/scfifo/scfifo.xci]

read_ip -quiet G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/vga_ram/vga_ram.xci
set_property used_in_implementation false [get_files -all g:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/vga_ram/vga_ram_ooc.xdc]
set_property is_locked true [get_files G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/sources_1/ip/vga_ram/vga_ram.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/constrs_1/new/NEHCPU.xdc
set_property used_in_implementation false [get_files G:/AbandonMIPS/AbandonMIPS/v1.0/Abandon_MIPS/src/NEHCPU_3/NEHCPU_3.srcs/constrs_1/new/NEHCPU.xdc]


synth_design -top nehcpu_sopc -part xc7a100tfgg676-2L


write_checkpoint -force -noxdef nehcpu_sopc.dcp

catch { report_utilization -file nehcpu_sopc_utilization_synth.rpt -pb nehcpu_sopc_utilization_synth.pb }
